version: '4'

services:

  kong:
    image: kong:3.0
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_NGINX_PROXY_REAL_IP_RECURSIVE: "on"
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - internal_network
      - public_network

  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - ./containers/kong/data:/var/lib/postgresql/data
    networks:
      - internal_network

  konga:
    image: pantsel/konga:latest
    restart: always
    ports:
      - "1337:1337"
    volumes:
      - ./containers/konga/data:/app/.tmp
    environment:
      NODE_ENV: "production"
    networks:
      - internal_network
      - public_network

networks:
  internal_network:
    driver: bridge
  public_network:
    driver: bridge
